# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40d12fb9bbd586f0ae3858270ab123dbd728abb0e3fdaf88c85485083fffb9c804063807096ef714404477c5901a43192f0abaf52464e70f3bc960a0c681ca7

test:
  secret_key_base: 23a926e767b6de059a1b07eaea24e4f251a066e23bd3ab351879f8bac025ee616d245e7b6d4bd85065c8d03861c00319b7390965cecd24e34bdbb9cb27712c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
